# Scan the image for vulnerabilities
variables:
  CONTAINER_SCAN_DISABLED: "false"
  SCRIPT_BRANCH: "main"
  SCRIPT_URL_PREFIX: "https://github.com/detecttechnologies/Gitlab-CI-CD-Templates/raw/${SCRIPT_BRANCH}"

include:
  - template: Jobs/Container-Scanning.gitlab-ci.yml

container_scanning:
  needs: ["build"]
  variables:
    CS_DOCKERFILE_PATH: "$DOCKERFILE_PATH"
    CS_IMAGE: "$CI_REGISTRY_IMAGE:$VERSION"
    GIT_STRATEGY: "fetch"
  rules:
    - if: $CONTAINER_SCAN_DISABLED == "true"
      when: never
    - if: $CI_COMMIT_TAG
      variables:
        VERSION: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        VERSION: "merge"
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        VERSION: "latest"
    - when: never