merge-request-to-source:
    stage: push
    image: python
    script:
        - git config --global user.email "Platformteam@detecttechnologies.com"
        - git config --global user.name "Detect Gitlab Bot"
        - bash -c "$(curl -fsSL https://github.com/detecttechnologies/Gitlab-CI-CD-Templates/raw/main/knowledge-portal/central/initiate-push-to-source.sh)"
    only:
        refs:
            - main
