merge-request-to-source:
    stage: push
    image: python
    script:
        - git config --global user.email "Platformteam@detecttechnologies.com"
        - git config --global user.name "Detect Gitlab Bot"
        - |
           # Check and reset to previous commit until commit message contains "docs:" keyword; else break out of loop  
            while true
            do
                commit_message=$(git log -1 --format=%B);
                if [[ ${commit_message} == *"docs:"* ]]
                then
                    git reset --soft HEAD~1;
                else
                    break;
                fi
            done
             
        - ./initiate_push.sh 
    only:
        refs:
            - main