# Sample TOML configuration file template

# Client information
[[client]]
name = "<CLIENT_NAME>"
region = "<REGION>"
ecs_cluster_name = "<ECS_CLUSTER_NAME>"

# AWS Credentials
aws_account_id = "<AWS_ACCOUNT_ID>"
aws_access_key_id = "<AWS_ACCESS_KEY_ID>"
aws_secret_access_key = "<AWS_SECRET_ACCESS_KEY>"

# EC2 Credentials
ec2_public_ip = "<EC2_PUBLIC_IP>"
ec2_private_key = """
-----BEGIN RSA PRIVATE KEY-----
<ec2_private_key>
-----END RSA PRIVATE KEY-----
"""

# Array of Client-specific Repositories
[[client.repos]]
name = "<REPO_NAME_1>"
type = "<REPO_TYPE>" # "fe" or "be"
task_definition_name = "<TASK_DEFINITION_NAME_1>"
service_name = "<SERVICE_NAME_1>"

# Array of Client-specific Repositories
[[client.repos]]
name = "<REPO_NAME_2>"
type = "<REPO_TYPE>" # "fe" or "be"
task_definition_name = "<TASK_DEFINITION_NAME_2>"
service_name = "<SERVICE_NAME_2>"
