stages:
  - validate

MR-title-check:
  stage: validate
  script:
    - |
      FIRST_CHAR="${CI_MERGE_REQUEST_TITLE%"${CI_MERGE_REQUEST_TITLE#?}"}"
      case "${FIRST_CHAR}" in
        [\u0000-\u007F]*)
          echo "Merge request title does not start with a unicode gitmoji. Validation failed."
          exit 1
          ;;
        *)
          echo "Merge request title starts with a non-ASCII(0-127) character, and possibly a unicode gitmoji. Validation passed."
          ;;
      esac
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always

docs-spellcheck:
  stage: validate
  image: python:slim
  before_script:
    - pip install codespell
    - shopt -s globstar # Enable globbing using '*' in the shell, for the main script
  script:
    - FILES_TO_SPELLCHECK=$( (ls **/*.py; ls **/*.md) | tr '\n' ' ')
    - echo "Spellchecking the following files - ${FILES_TO_SPELLCHECK}"
    - codespell ${FILES_TO_SPELLCHECK}
  rules:
    - if: '$CI_MERGE_REQUEST_LABELS =~ /skip-validation/'
      when: never
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always

services:
  - docker:dind

docs-markdownlint:
  image: docker:latest
  stage: validate
  script:
    - docker run -v $(pwd):/workspace -w /workspace ghcr.io/igorshubovych/markdownlint-cli:latest --disable MD033 MD013 MD034 MD041 MD024 MD036 -- .
  rules:
    - if: '$CI_MERGE_REQUEST_LABELS =~ /skip-validation/'
      when: never
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always