MR-title-check:
  stage: test
  needs: []
  script:
    - |
      FIRST_CHAR="${CI_MERGE_REQUEST_TITLE%"${CI_MERGE_REQUEST_TITLE#?}"}"
      case "${FIRST_CHAR}" in
        [\u0000-\u007F]*)
          echo "Merge request title does not start with a unicode gitmoji. Validation failed."
          exit 1
          ;;
        *)
          echo "Merge request title starts with a non-ASCII(0-127) character, and possibly a unicode gitmoji. Validation passed."
          ;;
      esac
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always

docs-spellcheck:
  stage: test
  needs: []
  image: python:slim
  before_script:
    - pip install codespell
    - shopt -s globstar # Enable globbing using '*' in the shell, for the main script
  script:
    - FILES_TO_SPELLCHECK=$( (ls **/*.py; ls **/*.md) | tr '\n' ' ')
    - echo "Spellchecking the following files - ${FILES_TO_SPELLCHECK}"
    - codespell ${FILES_TO_SPELLCHECK} 2>&1 | tee spellcheck-report.txt || true
  artifacts:
    paths:
      - spellcheck-report.txt
    expire_in: 1 week
  rules:
    - when: always

services:
  - docker:dind

docs-markdownlint:
  image: docker:latest
  stage: test
  needs: []
  script:
    - docker pull ghcr.io/igorshubovych/markdownlint-cli:latest
    - docker run -v $(pwd):/workspace -w /workspace ghcr.io/igorshubovych/markdownlint-cli:latest --disable MD033 MD013 MD034 MD041 MD024 MD036 -- . 2>&1 | tee markdownlint-report.txt || true
  artifacts:
    paths:
      - markdownlint-report.txt
    expire_in: 1 week
  rules:
    - when: always