release:
  stage: release
  image: alpine:latest
  tags:
    - amd64
  script:
    # 1) Install dependencies
    - apk add --no-cache curl jq zip

    # 2) Prepare files list
    - FILES_TO_ZIP=$(echo "$RELEASE_FILES" | tr ',' ' ')
    - echo "Zipping the following files: $FILES_TO_ZIP"

    # 3) Zip up your files
    - zip -r release.zip $FILES_TO_ZIP

    # 3) Handle the commit tag package:
    # 3a) Find any existing package with the same commit tag/version
    - >
      EXISTING_PACKAGE_ID=$(
        curl --silent \
          --header "JOB-TOKEN: $CI_JOB_TOKEN" \
          "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages?package_type=generic&package_name=${CI_PROJECT_NAME}" \
          | jq -r ".[] | select(.version == \"${VERSION}\").id"
      );
      echo "Existing package ID for ${VERSION}: $EXISTING_PACKAGE_ID";
      if [ -n "$EXISTING_PACKAGE_ID" ]; then
        echo "Deleting old package files for package ID $EXISTING_PACKAGE_ID for ${VERSION}...";
        PACKAGE_FILE_IDS=$(
          curl --silent \
            --header "JOB-TOKEN: $CI_JOB_TOKEN" \
            "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/${EXISTING_PACKAGE_ID}/package_files" \
            | jq -r ".[].id"
        );
        for FILE_ID in $PACKAGE_FILE_IDS; do
          curl --request DELETE \
               --header "JOB-TOKEN: $CI_JOB_TOKEN" \
               "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/${EXISTING_PACKAGE_ID}/package_files/${FILE_ID}";
        done
      fi

    # 3b) Upload the new release.zip for the commit tag
    - >
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" \
           --upload-file "release.zip" \
           "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${VERSION}/release.zip"

  rules:
    - if: $CI_COMMIT_TAG
      variables:
        VERSION: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        VERSION: "production"
    - if: $CI_COMMIT_BRANCH == "develop"
      variables:
        VERSION: "dev"

